# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
